# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RDR2cg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(199, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 181, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonsea = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonsea.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.pushButtonsea.setObjectName("pushButtonsea")
        self.verticalLayout.addWidget(self.pushButtonsea)
        self.pushButtonset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonset.setAutoDefault(True)
        self.pushButtonset.setObjectName("pushButtonset")
        self.verticalLayout.addWidget(self.pushButtonset)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setInputMask("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButtonsub = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonsub.setAutoDefault(True)
        self.pushButtonsub.setObjectName("pushButtonsub")
        self.verticalLayout.addWidget(self.pushButtonsub)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 199, 22))
        self.menubar.setObjectName("menubar")
        self.menurun = QtWidgets.QMenu(self.menubar)
        self.menurun.setToolTipsVisible(True)
        self.menurun.setObjectName("menurun")
        self.menuabout_me = QtWidgets.QMenu(self.menubar)
        self.menuabout_me.setObjectName("menuabout_me")
        MainWindow.setMenuBar(self.menubar)
        self.actionsingle = QtWidgets.QAction(MainWindow)
        self.actionsingle.setObjectName("actionsingle")
        self.actionmulti = QtWidgets.QAction(MainWindow)
        self.actionmulti.setObjectName("actionmulti")
        self.actionaddwinaction = QtWidgets.QAction(MainWindow)
        self.actionaddwinaction.setObjectName("actionaddwinaction")
        self.menurun.addAction(self.actionsingle)
        self.menurun.addAction(self.actionmulti)
        self.menubar.addAction(self.menurun.menuAction())
        self.menubar.addAction(self.menuabout_me.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RDR2cg"))
        self.pushButtonsea.setText(_translate("MainWindow", "search for RDR2.exe"))
        self.pushButtonset.setText(_translate("MainWindow", "set folder"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入4位数字密码"))
        self.pushButtonsub.setText(_translate("MainWindow", "submit"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">第一次使用需要搜索search for RDR2.exe大表哥的文件位置，之后就不再需要。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">可以直接搜索，等待时间长，具体看大表哥的安装位置。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果知道大表哥RDR2.exe的位置也可以直接选择set folder选择文件位置。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">密码是卡单的4位数字，大家数字一样就在一个战局，也可以不设置。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">点击菜单run选择single进入单人战局，选择multi进入多人战局。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">先运行本软件再运行游戏。</p></body></html>"))
        self.menurun.setTitle(_translate("MainWindow", "run"))
        self.menuabout_me.setTitle(_translate("MainWindow", "me"))
        self.actionsingle.setText(_translate("MainWindow", "single"))
        self.actionsingle.setShortcut(_translate("MainWindow", "Alt+S"))
        self.actionmulti.setText(_translate("MainWindow", "multi"))
        self.actionmulti.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionaddwinaction.setText(_translate("MainWindow", "addwinaction"))
        self.actionaddwinaction.setToolTip(_translate("MainWindow", "打开文件夹"))
